### ISSUE TITLE
OpenVPN Setup

### ISSUE THREAD

**Issue by aaron97neu** [aaron97neu/Discovery-World-Pong#13]
**Issue  by:** <a href='https://github.com/aaron97neu'>aaron97neu</a>
**Original date:** 2024-04-25 17:57:12 UTC
**Originally opened as:** <a href='https://github.com/Rockwell-Automation-Inc/Discovery-World-Pong/issues/91'>Rockwell-Automation-Inc/Discovery-World-Pong/issues/91</a>
**Original assignees:** <a href='https://github.com/aaron97neu'>aaron97neu</a>, <a href='https://github.com/pdschmir'>pdschmir</a>
**Status on 2024-11-04:** closed
<hr>

Dependent of #4

- [x] Setup OpenVPN Server and keys
- [x] Distribute OpenVPN keys
- [x] Configure static IP addresses for exhibits - client-config-dir and ifconfig-push seem to be the relevant configuration options
- [ ] Update readme with instructions
