### ISSUE TITLE
Integrate Teamviewer

### ISSUE THREAD

**Issue by aaron97neu** [aaron97neu/Discovery-World-Pong#14]
**Issue  by:** <a href='https://github.com/aaron97neu'>aaron97neu</a>
**Original date:** 2024-04-25 18:05:00 UTC
**Originally opened as:** <a href='https://github.com/Rockwell-Automation-Inc/Discovery-World-Pong/issues/92'>Rockwell-Automation-Inc/Discovery-World-Pong/issues/92</a>
**Original assignees:** <a href='https://github.com/pdschmir'>pdschmir</a>
**Status on 2024-11-04:** open
<hr>

Dependent of #4 

Discovery World has informed us that Teamviewer is their preferred remote access tool. Integrate and test it

- [x] Install teamviewer on exhibit
- [x] Add teamviewer install to post-install script
- [ ] Determine teamviewer licensing
- [ ] Install teamviewer on developer machines
- [ ] Test and verify
