### ISSUE TITLE
Add Sound

### ISSUE THREAD

**Issue by aaron97neu** [aaron97neu/Discovery-World-Pong#218]
As a patron, I want the exhibit to give me sound cues to make the exhibit more engaging and to help me navigate the exhibit with non-visual cues

**Depends** 

- **Priority** 4
- **Effort** 4

Tasks:
- [x] Coordinate speaker hardware with Discovery World
- [ ] Determine specific sound file types required
- [ ] Coordinate acquiring sound assets with Discovery World
- [ ] Add Speakers to physical twin
- [ ] prototype sound driven from docker containers
- [ ] Integrate sounds with project
- [ ] Test
- [ ] Verify

**Original Author:** aaron97neu
**Created At:** 2024-03-01T21:45:30Z
**Original State: open

**Previous Discussion:**

John
Emmerich
on
sound
design:
>
For
the
audio,
we
would
plan
to
add
an
external
(likely
ceiling
mounted)
to
the
area.
We
are
certainly
open
to
suggestions
on
tweaks
for
ease
of
implementation
and
look
forward
to
collaborating.
Where
should
sound
be?
Consider
separate
module
that
listens
for
MQTT
events
and
responds
accordingly

Risk
here
is
that
there
could
be
a
desync
between
visual
and
sound
cues

**Comment by aaron97neu** [comment]
Completed by #262
