### ISSUE TITLE
LED bar to follow patrons

### ISSUE THREAD

**Issue by aaron97neu** [aaron97neu/Discovery-World-Pong#228]
As a patron, I want an LED bar to follow my position laterally to help visualize my body movement.

Depends
Purchase and installation of an LED lightbar with individually addressable LEDs.

Priority 9
Effort 5

Tasks:
- [ ] Determine length of LED Strip needed
- [ ] Find a lightbar online which is individually addressable, large enough, and easily programmable.
- [ ] Find how to implement control of the lightbar into the program code.
- [ ] Program the lightbar to move back and forth depending on the lateral position of the player.

**Original Author:** dhudetz
**Created At:** 2023-11-30T18:58:17Z
**Original State: open

**Previous Discussion:**

This would be a good starting enhancement issue

These two options could work, but shorter lengths could give better density. Should also consider a diffuser, could help match the "retro" aesthetic of other parts of the physical setup

https://www.adafruit.com/product/306
https://www.adafruit.com/product/1461

Would likely need to pair with a RPI and watch MQTT messages or something

**Comment by aaron97neu** [comment]
Demonstrated by MSOE, not merged into main repo
